import {defineConfig} from 'oxlint';

const commonIgnore = ['**/.*', 'examples/**', 'docker', 'types/**', 'node_modules/**', 'coverage/**', 'dist/**'];

export const linter = defineConfig({
	plugins: ['typescript', 'unicorn', 'vitest', 'jsdoc', 'import', 'promise', 'node'],
	categories: {
		correctness: 'deny',
		suspicious: 'deny',
		pedantic: 'deny',
		perf: 'deny',
		style: 'off',
		restriction: 'off',
	},
	ignorePatterns: commonIgnore,
	env: {
		node: true,
	},
	rules: {
		'typescript/consistent-type-definitions': 'off',
		'typescript/no-confusing-void-expression': 'off',
		'typescript/no-unnecessary-condition': 'off',
		'typescript/restrict-template-expressions': 'off',
		'typescript/no-unused-vars': [
			'warn',
			{
				argsIgnorePattern: '^_',
			},
		],
		'vitest/no-conditional-expect': 'off',
		'vitest/valid-title': 'off',
		'vitest/expect-expect': 'off',
		'unicorn/catch-error-name': 'off',
		'unicorn/filename-case': 'off',
		'unicorn/prefer-top-level-await': 'off',
		'unicorn/no-array-for-each': 'off',
		'unicorn/no-useless-undefined': 'deny',
		'unicorn/no-process-exit': 'off',
		'unicorn/consistent-existence-index-check': 'off',
		'unicorn/escape-case': 'off',
		'unicorn/no-hex-escape': 'off',
		'unicorn/no-useless-error-capture-stack-trace': 'off',
		'unicorn/no-nested-ternary': 'off',
		'unicorn/no-immediate-mutation': 'off',
		'unicorn/no-object-as-default-parameter': 'off',
		'unicorn/require-array-join-separator': 'deny',
		'unicorn/numeric-separators-style': 'deny',
		'unicorn/number-literal-case': 'deny',
		'unicorn/no-null': 'off',
		'unicorn/switch-case-braces': 'off',
		'unicorn/no-array-reduce': 'off',
		'unicorn/no-array-sort': 'off',
		'unicorn/prefer-at': 'off',
		'unicorn/prefer-global-this': 'off',
		'unicorn/prefer-includes': 'off',
		'unicorn/prefer-logical-operator-over-ternary': 'off',
		'unicorn/prefer-code-point': 'off',
		'unicorn/prefer-date-now': 'off',
		'unicorn/prefer-dom-node-dataset': 'off',
		'unicorn/prefer-query-selector': 'off',
		'unicorn/prefer-prototype-methods': 'off',
		'unicorn/prefer-spread': 'off',
		'unicorn/prefer-string-raw': 'off',
		'unicorn/prefer-ternary': 'off',
		'unicorn/prefer-type-error': 'off',
		'jsdoc/require-param-type': 'off',
		'jsdoc/require-returns-type': 'off',
		'jsdoc/require-property-type': 'off',
		'no-inline-comments': 'off',
		'no-await-in-loop': 'off',
		'no-promise-executor-return': 'off',
		'import/no-named-as-default': 'off',
		'preserve-caught-error': 'off',
		'no-shadow': 'off',
		'max-lines-per-function': 'off',
		'max-dependencies': 'off',
		'import/max-dependencies': 'off',
		'max-lines': 'off',
		'no-new': 'off',
		'no-warning-comments': 'off',
		'jsdoc/require-param': 'off',
		'jsdoc/require-param-description': 'off',
		'require-await': 'off',
		'no-else-return': 'off',
		'no-useless-return': 'off',
		'max-classes-per-file': 'off',
		'import/no-named-as-default-member': 'off',
		'no-unmodified-loop-condition': 'off',
		'promise/always-return': 'off',
		'max-depth': 'off',
		radix: 'off',
		'eslint/no-underscore-dangle': 'off',
		'import/no-unassigned-import': 'off',
		'jest/consistent-test-it': 'off',
		'jest/expect-expect': 'off',
		'jest/max-expects': 'off',
		'jest/max-nested-describe': 'off',
		'jest/no-alias-methods': 'off',
		'jest/no-commented-out-tests': 'off',
		'jest/no-conditional-expect': 'off',
		'jest/no-conditional-in-test': 'off',
		'jest/no-confusing-set-timeout': 'off',
		'jest/no-deprecated-functions': 'off',
		'jest/no-disabled-tests': 'off',
		'jest/no-done-callback': 'off',
		'jest/no-duplicate-hooks': 'off',
		'jest/no-export': 'off',
		'jest/no-focused-tests': 'off',
		'jest/no-hooks': 'off',
		'jest/no-identical-title': 'off',
		'jest/no-interpolation-in-snapshots': 'off',
		'jest/no-jasmine-globals': 'off',
		'jest/no-large-snapshots': 'off',
		'jest/no-mocks-import': 'off',
		'jest/no-restricted-jest-methods': 'off',
		'jest/no-restricted-matchers': 'off',
		'jest/no-standalone-expect': 'off',
		'jest/no-test-prefixes': 'off',
		'jest/no-test-return-statement': 'off',
		'jest/no-unneeded-async-expect-function': 'off',
		'jest/no-untyped-mock-factory': 'off',
		'jest/padding-around-test-blocks': 'off',
		'jest/prefer-called-with': 'off',
		'jest/prefer-comparison-matcher': 'off',
		'jest/prefer-each': 'off',
		'jest/prefer-ending-with-an-expect': 'off',
		'jest/prefer-equality-matcher': 'off',
		'jest/prefer-expect-assertions': 'off',
		'jest/prefer-expect-resolves': 'off',
		'jest/prefer-hooks-in-order': 'off',
		'jest/prefer-hooks-on-top': 'off',
		'jest/prefer-jest-mocked': 'off',
		'jest/prefer-lowercase-title': 'off',
		'jest/prefer-mock-promise-shorthand': 'off',
		'jest/prefer-mock-return-shorthand': 'off',
		'jest/prefer-spy-on': 'off',
		'jest/prefer-strict-equal': 'off',
		'jest/prefer-to-be': 'off',
		'jest/prefer-to-contain': 'off',
		'jest/prefer-to-have-been-called': 'off',
		'jest/prefer-to-have-been-called-times': 'off',
		'jest/prefer-to-have-length': 'off',
		'jest/prefer-todo': 'off',
		'jest/require-hook': 'off',
		'jest/require-to-throw-message': 'off',
		'jest/require-top-level-describe': 'off',
		'jest/valid-describe-callback': 'off',
		'jest/valid-expect': 'off',
		'jest/valid-title': 'off',
		'oxc/no-async-await': 'off',
		'oxc/no-map-spread': 'off', // TODO: consider enabling
		'oxc/no-optional-chaining': 'off',
		'oxc/no-rest-spread-properties': 'off',
		'typescript/strict-boolean-expressions': 'off',
		'typescript/no-unsafe-type-assertion': 'off',
		'typescript/no-unsafe-member-access': 'off',
		'typescript/no-unsafe-call': 'off',
		'typescript/no-unsafe-assignment': 'off',
		'typescript/no-unsafe-return': 'off',
		'typescript/no-unsafe-argument': 'off',
		'typescript/no-explicit-any': 'off',
		'typescript/return-await': 'off',
		'typescript/switch-exhaustiveness-check': 'off',
		'typescript/no-base-to-string': 'off',
		'typescript/no-misused-promises': 'off',
		'typescript/require-await': 'off',
		'vitest/max-expects': 'off',
		'vitest/no-conditional-in-test': 'off',
		'vitest/no-hooks': 'off',
		'vitest/no-importing-vitest-globals': 'off',
		'vitest/prefer-describe-function-title': 'off',
		'vitest/prefer-expect-assertions': 'off',
		'vitest/prefer-to-be-falsy': 'off', // NOTE: Pick strictness: keep prefer-strict-boolean-matchers, disable truthy/falsy rules.
		'vitest/prefer-to-be-truthy': 'off', // NOTE: Pick strictness: keep prefer-strict-boolean-matchers, disable truthy/falsy rules.
		'vitest/require-test-timeout': 'off',
	},
	overrides: [
		{
			files: ['src/frontend/**/*.{js,ts}'],
			env: {
				browser: true,
			},
		},
		{
			files: ['**/*.test.ts'],
			rules: {
				'typescript/no-unsafe-argument': 'off',
				'typescript/no-unsafe-call': 'off',
				'typescript/no-unsafe-member-access': 'off',
				'typescript/no-unsafe-assignment': 'off',
				'typescript/no-unsafe-return': 'off',
				'typescript/no-explicit-any': 'off',
				'typescript/no-floating-promises': 'off',
				'typescript/no-unused-vars': 'off',
				'typescript/dot-notation': 'off',
				'typescript/prefer-nullish-coalescing': 'off',
				'typescript/no-unnecessary-condition': 'off',
				'typescript/unbound-method': 'off',
				'unicorn/no-useless-undefined': 'off',
				'unicorn/consistent-function-scoping': 'off',
				'unicorn/no-await-expression-member': 'off',
				'unicorn/prefer-dom-node-append': 'off',
			},
		},
	],
});

export const formatter = {
	printWidth: 160,
	embeddedLanguageFormatting: 'off',
	useTabs: true,
	singleQuote: true,
	bracketSpacing: false,
	ignorePatterns: [...commonIgnore, '*.md', '*.json', '*.yaml'],
	overrides: [
		{
			files: ['src/**/*.{scss,css}'],
			options: {
				singleQuote: false,
			},
		},
	],
};