// flow-typed signature: 45df983be47fd5ef25e8449dc2e4435e
// flow-typed version: <<STUB>>/connect-multiparty_v^2.1.1/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'connect-multiparty'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'connect-multiparty' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'connect-multiparty/index' {
  declare module.exports: $Exports<'connect-multiparty'>;
}
declare module 'connect-multiparty/index.js' {
  declare module.exports: $Exports<'connect-multiparty'>;
}
