// flow-typed signature: 8aeb3831d7b727fd782ff4d7336d57b6
// flow-typed version: <<STUB>>/http-parser-js_v^0.4.11/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'http-parser-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'http-parser-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'http-parser-js/http-parser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'http-parser-js/http-parser.js' {
  declare module.exports: $Exports<'http-parser-js/http-parser'>;
}
