import type { Request, Response } from 'express';
import type { Connection } from 'oracledb';
import type { argObjType, fileUploadType, environmentType, configPlSqlHandlerType, argsType } from '../../types.ts';
import type { Cache } from '../../util/cache.ts';
export type ProcedureNameCache = Cache<string>;
export type ArgumentCache = Cache<argsType>;
/**
 * Invoke the Oracle procedure and return the page content
 *
 * @param req - The req object represents the HTTP request.
 * @param res - The res object represents the HTTP response that an Express app sends when it gets an HTTP request.
 * @param argObj - - The arguments of the procedure to invoke.
 * @param cgiObj - The cgi of the procedure to invoke.
 * @param filesToUpload - Array of files to be uploaded
 * @param options - the options for the middleware.
 * @param databaseConnection - Database connection.
 * @param procedureNameCache - The procedure name cache.
 * @param argumentCache - The argument cache.
 * @returns Promise resolving to the page content generated by the executed procedure
 */
export declare const invokeProcedure: (req: Request, res: Response, argObj: argObjType, cgiObj: environmentType, filesToUpload: fileUploadType[], options: configPlSqlHandlerType, databaseConnection: Connection, procedureNameCache: ProcedureNameCache, argumentCache: ArgumentCache) => Promise<void>;
