DROP TABLE DocTable;

CREATE TABLE DocTable
(
	NAME			VARCHAR(128) UNIQUE NOT NULL,
	MIME_TYPE		VARCHAR(128), 
	DOC_SIZE		NUMBER, 
	DAD_CHARSET		VARCHAR(128), 
	LAST_UPDATED	DATE, 
	CONTENT_TYPE	VARCHAR(128), 
	CONTENT			LONG RAW, 
	BLOB_CONTENT	BLOB
);
