name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x, 25.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Verify pnpm
        run: pnpm --version

      # NOTE: We must install the Playwright dependencies because we will run the web integration tests 
      - name: Install Playwright Browsers & Deps
        run: npx playwright install --with-deps chromium
        
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run CI (lint, types, build, test, coverage)
        run: npm run ci

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2

      - name: Integration test
        run: pnpm run integration-test
